# Generated by Django 5.0.1 on 2024-03-12 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, null=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('user_name', models.CharField(primary_key=True, serialize=False)),
                ('roll_number', models.CharField(blank=True, null=True)),
                ('reg_num', models.CharField(blank=True, null=True)),
                ('email_id', models.CharField(blank=True, null=True)),
                ('mobille_num', models.CharField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('branch', models.CharField(blank=True, null=True)),
                ('semester', models.CharField(blank=True, null=True)),
                ('category', models.CharField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='practice.course')),
                ('semester', models.CharField(blank=True, null=True)),
                ('grades', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enrollment',
                'managed': False,
            },
        ),
    ]
