# Generated by Django 5.0.1 on 2024-02-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registration_no',
            field=models.IntegerField(),
        ),
    ]
